<!--------------------------------------------------------------------
Generated Application: lightwiresample
Generated Date: July 24 2007
Generated By: ColdBox Ant Task.
---------------------------------------------------------------------->
<!-----------------------------------------------------------------------Author 	 :	Your NameDate     :	September 25, 2005Description : 				This is a ColdBox event handler for general methods.Please note that the extends needs to point to the eventhandler.cfcin the ColdBox system directory.extends = coldbox.system.eventhandler	-----------------------------------------------------------------------><cfcomponent name="general" extends="coldbox.system.eventhandler" output="false">		<!--- This init format is mandatory if you are writing init code else is optional, 	      include the super.init(arguments.controller). 	<cffunction name="init" access="public" returntype="any" output="false">		<cfargument name="controller" type="any">		<cfset super.init(arguments.controller)>		<!--- Any constructor code here --->		<cfreturn this>	</cffunction>	--->	<cffunction name="dspHome" access="public" returntype="void" output="false">		<cfargument name="Event" type="coldbox.system.beans.requestContext">		<cfset var rc = event.getCollection()>
		<!--- Get Beans --->
		<cfset rc.ProductService = getPlugin("ioc").getBean("ProductService")>
		<cfset rc.CategoryService = getPlugin("ioc").getBean("CategoryService")>
		<cfset rc.Product = getPlugin("ioc").getBean("Product")>		<!--- Set the View To Display, after Logic --->		<cfset Event.setView("home")>	</cffunction>		</cfcomponent>