<!--------------------------------------------------------------------
Generated Application: TransferSample
Generated Date: March 19 2007
Generated By: ColdBox Ant Task.
---------------------------------------------------------------------->
<!-----------------------------------------------------------------------
Template :  Application.cfm 
Author 	 :	Luis Majano
Date     :	January 22, 2006
Description : 			
	This is a protection Application cfm for the config file. You do not
	need to modify this file
----------------------------------------------------------------------->
<cfabort>