<!--------------------------------------------------------------------
Generated Application: TransferSample
Generated Date: March 19 2007
Generated By: ColdBox Ant Task.
---------------------------------------------------------------------->
<cfapplication name="#hash(getCurrentTemplatePath())#"			   sessionmanagement="yes"			   sessiontimeout="#CreateTimeSpan(0,0,30,0)#"			   setclientcookies="true">