name: ColdBox LTS Flow

on:
  push:
    branches:
      - "releases/**"

jobs:
  #############################################
  # Tests First baby! We fail, no build :(
  #############################################
  tests:
    uses: ./.github/workflows/tests.yml
    secrets: inherit

  ##########################################################################################
  # Format Source Code
  ##########################################################################################
  format:
    name: Code Auto-Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Auto-format
        uses: Ortus-Solutions/commandbox-action@v1.0.3
        with:
          cmd: run-script format

      - name: Commit Format Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Apply cfformat changes
          push_options: --force
