name: Pull Requests

on:
  pull_request:
    branches:
      - development
      - "releases/**"
      - patch/pr-cfformat-workflow # TESTING!!

jobs:
  format:
    name: Format
    runs-on: ubuntu-20.04
    permissions:
      pull-requests: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - uses: Ortus-Solutions/commandbox-action@v1.0.2
        with:
          # For security reasons, we use our OWN cfformat command - not trusting the one in the PR
          cmd: cfformat run system/**/*.cfc,tests/specs/**/*.cfc --overwrite

      - name: Commit Format Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply cfformat changes

  tests:
    uses: ./.github/workflows/tests.yml
    secrets: inherit
